image:
  file: .gitpod.dockerfile
tasks:
  - init: mysql -u root -e "create database laravel";
  - before: composer install
    command: php -r "copy('.env.example','.env');" && php artisan key:generate
