image:
  file: .gitpod.dockerfile
tasks:
  - init: mysql -u root -e "create database laravel";
  - init: composer install
  - init: php -r "copy('.env.example','.env');" && php artisan key:generate
  - command: php artisan serve --host=0.0.0.0
